# Generated by Django 5.1.6 on 2025-02-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
            },
        ),
        migrations.CreateModel(
            name="RefBookVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="Версия")),
                ("date", models.DateField(verbose_name="Дата начала действия версии")),
                (
                    "ref_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="refbooks.refbook",
                        verbose_name="Справочник",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefBookElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код элемента")),
                (
                    "value",
                    models.CharField(max_length=300, verbose_name="Значение элемента"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="refbooks.refbookversion",
                        verbose_name="Версия справочника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент справочника",
                "verbose_name_plural": "Элементы справочника",
                "unique_together": {("version", "code")},
            },
        ),
    ]
