# Generated by Django 5.1.6 on 2025-02-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refbooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refbookversion",
            options={
                "verbose_name": "Версия справочника",
                "verbose_name_plural": "Версии справочника",
            },
        ),
        migrations.RenameField(
            model_name="refbookversion",
            old_name="ref_book",
            new_name="refbook",
        ),
    ]
